-- Run this in Supabase SQL Editor before deploying.
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'cashier' check (role in ('admin', 'cashier')),
  created_at timestamptz not null default now()
);

create table if not exists public.menu (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(12,2) not null check (price >= 0),
  image text,
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
    table_no text,
  items jsonb not null default '[]'::jsonb,
  total numeric(12,2) not null check (total >= 0),
  status text not null default 'Pending' check (status in ('Pending', 'Preparing', 'Completed', 'Cancelled')),
  cashier_id uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.menu (name, price, image)
select *
from (values
  ('Chechebsa', 150, 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&q=80'),
  ('Special Ful', 120, 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80'),
  ('Egg Firfir', 140, 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&q=80'),
  ('Fetira with Honey', 160, 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=600&q=80'),
  ('Ethiopian Tea', 20, 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&q=80'),
  ('Coffee', 30, 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80')
) as items(name, price, image)
where not exists (select 1 from public.menu);

insert into public.menu (name, price, image)
select 'Bread', 15, 'icon.svg'
where not exists (select 1 from public.menu where lower(name) = 'bread');

insert into public.menu (name, price, image)
select 'Injera', 20, 'icon.svg'
where not exists (select 1 from public.menu where lower(name) = 'injera');

  -- Cashiers can edit only their own order items. They cannot update status,
  -- delete orders, or read another cashier's orders.
  alter table public.orders alter column table_no drop not null;
  drop policy if exists "Cashiers update own orders" on public.orders;
  create policy "Cashiers update own orders" on public.orders for update to authenticated
  using (cashier_id = auth.uid())
  with check (cashier_id = auth.uid());

alter table public.profiles enable row level security;
alter table public.menu enable row level security;
alter table public.orders enable row level security;

create or replace function public.current_user_role()
returns text language sql stable security definer set search_path = public
as $$ select role from public.profiles where id = auth.uid() $$;

create policy "Users can read their profile" on public.profiles for select to authenticated using (id = auth.uid());
create policy "Everyone can read menu" on public.menu for select to authenticated using (true);
create policy "Admins manage menu" on public.menu for all to authenticated using (public.current_user_role() = 'admin') with check (public.current_user_role() = 'admin');
create policy "Cashiers create orders" on public.orders for insert to authenticated with check (cashier_id = auth.uid());
create policy "Users read orders" on public.orders for select to authenticated using (public.current_user_role() = 'admin' or cashier_id = auth.uid());
create policy "Admins update orders" on public.orders for update to authenticated using (public.current_user_role() = 'admin') with check (public.current_user_role() = 'admin');
create policy "Admins delete orders" on public.orders for delete to authenticated using (public.current_user_role() = 'admin');

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$ begin
  insert into public.profiles (id, full_name) values (new.id, coalesce(new.raw_user_meta_data->>'full_name', new.email));
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

-- Promote the owner after creating their account:
-- update public.profiles set role = 'admin' where id = 'YOUR-AUTH-USER-ID';
